--------------------------------------------------------------------------------
-- Header
--------------------------------------------------------------------------------

-- GitHub: https://github.com/VowSoftware/starly

--------------------------------------------------------------------------------
-- Dependencies
--------------------------------------------------------------------------------

local m_starly = require "starly.starly"

--------------------------------------------------------------------------------
-- Properties
--------------------------------------------------------------------------------

go.property("behavior", hash("center"))
go.property("viewport_x", 0)
go.property("viewport_y", 0)
go.property("viewport_width", 960)
go.property("viewport_height", 640)
go.property("near", -1)
go.property("far", 1)
go.property("zoom", 1)
go.property("zoom_max", 1)
go.property("zoom_min", 1)
go.property("boundary", false)
go.property("boundary_x", 0)
go.property("boundary_y", 0)
go.property("boundary_width", 0)
go.property("boundary_height", 0)

--------------------------------------------------------------------------------
-- Engine Functions
--------------------------------------------------------------------------------

function init(self)
	m_starly.create(go.get_id())
end

function final(self)
	m_starly.destroy(go.get_id())
end