--------------------------------------------------------------------------------
-- Header
--------------------------------------------------------------------------------

-- GitHub: https://github.com/VowSoftware/starly

--------------------------------------------------------------------------------
-- Dependencies
--------------------------------------------------------------------------------

local m_starly = require "starly.starly"

--------------------------------------------------------------------------------
-- Constants
--------------------------------------------------------------------------------

local c_id_starly = hash("/starly")

-- Default clear color, specified in *game.project*.
local c_clear_color = vmath.vector4(sys.get_config_number("render.clear_color_red"), sys.get_config_number("render.clear_color_green"), sys.get_config_number("render.clear_color_blue"), sys.get_config_number("render.clear_color_alpha"))

local c_default_buffer_values = { [graphics.BUFFER_TYPE_COLOR0_BIT] = c_clear_color }

--------------------------------------------------------------------------------
-- Variables
--------------------------------------------------------------------------------

local v_predicate_tile = nil

--------------------------------------------------------------------------------
-- Engine Functions
--------------------------------------------------------------------------------

function init(self)
	v_predicate_tile = render.predicate({ "tile" })
end

function update(self, dt)
	m_starly.activate(c_id_starly)
	render.clear(c_default_buffer_values)
	render.set_blend_func(graphics.BLEND_FACTOR_SRC_ALPHA, graphics.BLEND_FACTOR_ONE_MINUS_SRC_ALPHA)
	render.enable_state(graphics.STATE_BLEND)
	render.draw(v_predicate_tile)
	render.disable_state(graphics.STATE_BLEND)
end