--------------------------------------------------------------------------------
-- Header
--------------------------------------------------------------------------------

-- GitHub: https://github.com/VowSoftware/starly

--------------------------------------------------------------------------------
-- Dependencies
--------------------------------------------------------------------------------

local m_starly = require "starly.modules.starly"

--------------------------------------------------------------------------------
-- Constants
--------------------------------------------------------------------------------

-- Message ids.
local c_msg_acquire_input_focus = hash("acquire_input_focus")

-- Action ids in `on_input()`.
local c_mouse_wheel_up = hash("mouse_wheel_up")
local c_mouse_wheel_down = hash("mouse_wheel_down")
local c_mouse_button_middle = hash("mouse_button_middle")
local c_key_space = hash("key_space")

-- Game object ids.
local c_id_starly = hash("/starly")

--------------------------------------------------------------------------------
-- Variables
--------------------------------------------------------------------------------

-- Determines if the middle mouse button is down, allowing for camera movement.
local v_moving = false

--------------------------------------------------------------------------------
-- Engine Functions
--------------------------------------------------------------------------------

function init(self)
	msg.post(msg.url(), c_msg_acquire_input_focus)
end

function on_input(self, action_id, action)
	if not action_id then
		if v_moving then
			local offset = vmath.vector3(-action.screen_dx, -action.screen_dy, 0)
			m_starly.move(c_id_starly, offset)
		end
	elseif action.pressed then
		if action_id == c_mouse_wheel_up then
			m_starly.zoom(c_id_starly, 4)
		elseif action_id == c_mouse_wheel_down then
			m_starly.zoom(c_id_starly, -4)
		elseif action_id == c_mouse_button_middle then
			v_moving = true
		elseif action_id == c_key_space then
			m_starly.shake(c_id_starly, 10, 0.125, 10, 0.75, 0.75)
		end
	elseif action.released then
		if action_id == c_mouse_button_middle then
			v_moving = false
		end
	end
end